apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: maas-api-models-auth-policy
  namespace: opendatahub
spec:
  rules:
    authentication:
      service-account-tokens:
        kubernetesTokenReview:
          audiences:
            - 'https://kubernetes.default.svc'
            - maas-default-gateway-sa
        metrics: false
        priority: 0
    response:
      success:
        headers:
          X-MaaS-Group:
            metrics: false
            plain:
              selector: auth.identity.user.groups.@tostr
            priority: 0
          X-MaaS-Username:
            metrics: false
            plain:
              selector: auth.identity.user.username
            priority: 0
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: maas-api-route