# RBAC for maas-api namespace - allows app to access ConfigMaps in maas-api
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maas-toolbox-role
  namespace: maas-api
  labels:
    app: maas-toolbox
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maas-toolbox-rolebinding
  namespace: maas-api
  labels:
    app: maas-toolbox
subjects:
- kind: ServiceAccount
  name: maas-toolbox-sa
  namespace: maas-toolbox
roleRef:
  kind: Role
  name: maas-toolbox-role
  apiGroup: rbac.authorization.k8s.io

